services:
  openwebui:
    image: mareekkk/canary-chat:latest
    build:
      context: /home/mark/llm-server/openwebui         
      dockerfile: Dockerfile 
    container_name: openwebui
    user: "${UID}:${GID}"
    ports:
      - "8080:8080"
    dns:
      - 8.8.8.8
      - 1.1.1.1
      - 192.168.20.1
    environment:
      UID: "${UID}"
      GID: "${GID}"
      WEBUI_AUTH: "${WEBUI_AUTH}"
      WEBUI_USERNAME: "${WEBUI_USERNAME}"
      WEBUI_PASSWORD: "${WEBUI_PASSWORD}"
      DATABASE_URL: "${DATABASE_URL}"
      WEBUI_SECRET_KEY: "${WEBUI_SECRET_KEY}"
      OLLAMA_BASE_URL: "${OLLAMA_BASE_URL}"
    volumes:
      - ../volumes/openwebui:/app/backend/data
    restart: unless-stopped
    depends_on:
      - openwebui-postgres

  openwebui-postgres:
    image: pgvector/pgvector:pg15
    container_name: openwebui-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ../volumes/openwebui/postgres:/var/lib/postgresql/data
